services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./.env
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - airflow
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  airflow-init:
    image: my_airflow:1.0.0
    container_name: init
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    env_file:
      - ./.env
      - ./.hadoop.env
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - YARN_CONF_DIR=/opt/hadoop/etc/hadoop
    entrypoint: 
      - bash
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./include:/opt/airflow/include
      - ./data:/opt/airflow/data
      - ./hadoop-config:/opt/hadoop/etc/hadoop
    networks:
      - airflow
    
  webserver:
    image: my_airflow:1.0.0
    container_name: webserver
    depends_on:
      mysql:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - ./.env
      - ./.hadoop.env
    environment:
      - SPARK_HOME=/home/airflow/.local/lib/python3.10/site-packages/pyspark
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - YARN_CONF_DIR=/opt/hadoop/etc/hadoop
      - AIRFLOW__SPARK__SPARK_HOME=/home/airflow/.local/lib/python3.10/site-packages/pyspark
      - AIRFLOW__SPARK__SPARK_BINARY=/home/airflow/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit
      - JAVA_HOME=/usr/lib/jvm/default-java
    command: airflow webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./include:/opt/airflow/include
      - ./data:/opt/airflow/data
      - ./hadoop-config:/opt/hadoop/etc/hadoop
    networks:
      - airflow
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler:
    image: my_airflow:1.0.0
    container_name: scheduler
    depends_on:
      mysql:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - ./.env
      - ./.hadoop.env
    environment:
      - SPARK_HOME=/home/airflow/.local/lib/python3.10/site-packages/pyspark
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - YARN_CONF_DIR=/opt/hadoop/etc/hadoop
      - AIRFLOW__SPARK__SPARK_HOME=/home/airflow/.local/lib/python3.10/site-packages/pyspark
      - AIRFLOW__SPARK__SPARK_BINARY=/home/airflow/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit
      - JAVA_HOME=/usr/lib/jvm/default-java
    command: airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./include:/opt/airflow/include
      - ./data:/opt/airflow/data
      - ./hadoop-config:/opt/hadoop/etc/hadoop
    networks:
      - airflow
    restart: unless-stopped
  
volumes:
  mysql_data:
    driver: local

networks:
  airflow:
    driver: bridge