services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop-config:/etc/hadoop/conf
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - airflow

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./hadoop-config:/etc/hadoop/conf
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    networks:
      - airflow

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    ports:
      - "8088:8088"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
    volumes:
      - ./hadoop-config:/etc/hadoop/conf
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864
    depends_on:
      - namenode
      - datanode
    networks:
      - airflow

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    ports:
      - "8042:8042"
    volumes:
      - ./hadoop-config:/etc/hadoop/conf
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 resourcemanager:8088 datanode:9864
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    networks:
      - airflow

  spark:
    image: bitnami/spark:3.5.1
    container_name: spark
    command: sleep infinity
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./hadoop-config:/etc/hadoop/conf
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - YARN_CONF_DIR=/etc/hadoop/conf
      - SPARK_MODE=client
      - SPARK_MASTER=yarn
      - SPARK_SUBMIT_DEPLOYMODE=client
    depends_on:
      - resourcemanager
      - namenode
      - nodemanager
    networks:
      - airflow

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    ports:
      - "8188:8188"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - ./hadoop-config:/etc/hadoop/conf
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    networks:
      - airflow

networks:
  airflow:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
